# Generated by Django 4.2.27 on 2025-12-12 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codice', models.AutoField(primary_key=True, serialize=False)),
                ('cf', models.CharField(max_length=16, unique=True, verbose_name='Codice Fiscale')),
                ('rag_soc', models.CharField(db_column='ragSoc', max_length=100, verbose_name='Ragione Sociale')),
                ('indirizzo', models.CharField(max_length=100)),
                ('citta', models.CharField(max_length=60, verbose_name='Città')),
            ],
            options={
                'verbose_name_plural': 'Clienti',
                'db_table': 'cliente',
                'ordering': ['rag_soc'],
            },
        ),
        migrations.CreateModel(
            name='Fattura',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('imponibile', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totale', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Fatture',
                'db_table': 'fattura',
            },
        ),
        migrations.CreateModel(
            name='Utenza',
            fields=[
                ('codice', models.AutoField(primary_key=True, serialize=False)),
                ('data_apertura', models.DateField(db_column='dataAp')),
                ('indirizzo', models.CharField(max_length=100)),
                ('citta', models.CharField(max_length=60, verbose_name='Città')),
                ('stato', models.CharField(choices=[('attivo', 'Attivo'), ('inattivo', 'Inattivo')], default='attivo', max_length=10)),
                ('data_chiusura', models.DateField(blank=True, db_column='dataCh', null=True)),
                ('cliente', models.ForeignKey(db_column='cliente', on_delete=django.db.models.deletion.CASCADE, related_name='utenze', to='core.cliente')),
            ],
            options={
                'verbose_name_plural': 'Utenze',
                'db_table': 'utenza',
            },
        ),
        migrations.CreateModel(
            name='Lettura',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('valore', models.IntegerField()),
                ('fattura', models.ForeignKey(blank=True, db_column='fattura', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fattura')),
                ('utenza', models.ForeignKey(db_column='utenza', on_delete=django.db.models.deletion.CASCADE, related_name='letture', to='core.utenza')),
            ],
            options={
                'verbose_name_plural': 'Letture',
                'db_table': 'lettura',
            },
        ),
    ]
