# Generated by Django 4.2.27 on 2025-12-13 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettura',
            name='fattura',
            field=models.ForeignKey(blank=True, db_column='fattura', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letture', to='core.fattura'),
        ),
    ]
